In [1]:
import numpy as np

In [2]:
a = np.full((2,3,4),4)
a


array([[[4, 4, 4, 4],
        [4, 4, 4, 4],
        [4, 4, 4, 4]],

       [[4, 4, 4, 4],
        [4, 4, 4, 4],
        [4, 4, 4, 4]]])

In [3]:
b= np.ones((2,3,4))
b

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [4]:
a = np.empty((5,5,5))
a

array([[[0.00000000e+000, 6.95183816e-310, 1.99108455e-321,
         1.28447099e-311, 1.28447140e-311],
        [6.95183823e-310, 1.39052262e-309, 0.00000000e+000,
         1.06099790e-313, 4.94065646e-324],
        [0.00000000e+000, 0.00000000e+000, 6.95183823e-310,
         6.95183823e-310, 1.28447149e-311],
        [1.28447151e-311, 1.28447151e-311, 1.28446193e-311,
         0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         1.02359509e-306, 3.82365689e-297]],

       [[3.82440351e-297, 1.06788918e-287, 4.58792637e-278,
         1.97109091e-268, 1.07598055e-282],
        [3.63765773e-249, 5.13120199e-244, 3.82265086e-297,
         1.02452389e-234, 1.34024093e-229],
        [0.00000000e+000, 1.44347913e-315, 2.91756361e-257,
         1.44932313e-311, 4.39012211e-225],
        [5.60683073e-249, 3.56942936e-306, 1.57696606e-234,
         8.10395444e-206, 6.22319660e-119],
        [2.90819536e-309, 8.95676144e-312, 2.10966031e-321,
  

In [5]:
#arange takes starting value and ending value and also the step size between each value to generate an array
x_value =np.arange(0,1000,5)
x_value

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190,
       195, 200, 205, 210, 215, 220, 225, 230, 235, 240, 245, 250, 255,
       260, 265, 270, 275, 280, 285, 290, 295, 300, 305, 310, 315, 320,
       325, 330, 335, 340, 345, 350, 355, 360, 365, 370, 375, 380, 385,
       390, 395, 400, 405, 410, 415, 420, 425, 430, 435, 440, 445, 450,
       455, 460, 465, 470, 475, 480, 485, 490, 495, 500, 505, 510, 515,
       520, 525, 530, 535, 540, 545, 550, 555, 560, 565, 570, 575, 580,
       585, 590, 595, 600, 605, 610, 615, 620, 625, 630, 635, 640, 645,
       650, 655, 660, 665, 670, 675, 680, 685, 690, 695, 700, 705, 710,
       715, 720, 725, 730, 735, 740, 745, 750, 755, 760, 765, 770, 775,
       780, 785, 790, 795, 800, 805, 810, 815, 820, 825, 830, 835, 840,
       845, 850, 855, 860, 865, 870, 875, 880, 885, 890, 895, 90

In [6]:
#line space is similar to arange takes starting and ending values where as as last element is to how many elements are needed
x_value = np.linspace(0,100,12)
x_value

array([  0.        ,   9.09090909,  18.18181818,  27.27272727,
        36.36363636,  45.45454545,  54.54545455,  63.63636364,
        72.72727273,  81.81818182,  90.90909091, 100.        ])

In [7]:
#arthamatic operations
#when a python list is mul by any number it repeats it self where as in numpy the array is multiplied with the number
l1 =[1,2,3,4,5]
l2 =[6,7,8,9,10]
a1= np.array(l1)
a2= np.array(l2)

print(l1*5) #all operations are not applicable 
print(a1*5)# all operatins are applicable
print(a1*a2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 5 10 15 20 25]
[ 6 14 24 36 50]


In [8]:
#mathamatical functions
# functions such as sqrt,sin,cos,log,log2,exp...
a = np.array([[1,2,3],
             [4,5,6]])
np.sin(a)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
a = np.array([1,2,3])
a = np.append(a,[4,5,6])
a
b= np.insert(a,4,[9,8,7])
b


array([1, 2, 3, 4, 9, 8, 7, 5, 6])

In [10]:
#delete
a = np.array([[1,2,3],
             [4,5,6]])

a=np.delete(a,0,0)
a
# frst value stands for rows 0 is the first row and 1 is the second row
#second value stands for columns 0 stands for first and so on 


array([[4, 5, 6]])

In [11]:
#stuctural methods
a= np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15],
              [16,17,18,19,20]])
a= a.reshape((5,4))
a
#flatten,ravel
#transposing
b= a.transpose()
#c= a.T   transpose can simple done by just providing T 
b
#a.swapaxes function is used similarly but when a higher dimention array is present and only required axis are to be transposed swap axis is used 

array([[ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19],
       [ 4,  8, 12, 16, 20]])

In [12]:
#concatinating, merging 
a= np.array([[1,2,3,4,5],
              [6,7,8,9,10]])
b = np.array([[11,12,13,14,15],
              [16,17,18,19,20]])


a1 = np.concatenate((a,b),axis=1)  # when axis is 0 the rows are added when its 1 values are added to  columns
a1    

#stack adds two arrays into two dimention with out making it into 1 
b1 = np.stack((a,b))
b1

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [13]:
a= np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15],
              [16,17,18,19,20]])
#split
b =a.T
b = np.split(b,2,axis=1)
b

[array([[ 1,  6],
        [ 2,  7],
        [ 3,  8],
        [ 4,  9],
        [ 5, 10]]),
 array([[11, 16],
        [12, 17],
        [13, 18],
        [14, 19],
        [15, 20]])]

In [15]:
a= np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15],
              [16,17,18,19,20]])

b = np.split(a,2)
b


[array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]),
 array([[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]])]

In [19]:
print(np.min(a))
print(np.max(a))
print(np.mean(a))
print(np.std(a))
print(np.sum(a))
print(np.median(a))

1
20
10.5
5.766281297335398
210
10.5


In [28]:
number=np.random.randint(100)
number

62

In [30]:
numbers = np.random.randint(0,100,size=(3,3,4),)
numbers

array([[[31, 17, 55, 88],
        [13, 64, 62, 84],
        [43, 65, 53, 64]],

       [[19, 51, 80, 69],
        [44, 31, 57, 12],
        [77,  1,  1, 78]],

       [[26, 61, 87, 57],
        [78, 81, 87, 93],
        [95, 75, 80, 66]]])

In [79]:
numbers = np.random.randint(0,101,(10,10))
print(np.mean(numbers))

51.93


In [98]:
number = np.random.binomial(1,0.5,(1,100))
print (np.mean(number))

0.43
