<a href="https://colab.research.google.com/github/Jayakrishna143/numpy/blob/main/Numpy_assignment_day_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### NumPy Exercises
##### Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.
##### IMPORTANT NOTE! Make sure you don't run the cells directly above the example output shown, otherwise you will end up writing over the example output!

##### import numpy as np


###### 1. Write a NumPy program to find the missing data in a given array.

In [1]:
### code here
import numpy as np
Original_array = np.array([3, 2, np.nan, 1, 10, 12, 10, 9, 5, np.nan, 1, np.nan]).reshape(3, 4)
print(f'Original_array:\n{Original_array} \nFind the missing data of the said array: \n {np.isnan(Original_array)}')

Original_array:
[[ 3.  2. nan  1.]
 [10. 12. 10.  9.]
 [ 5. nan  1. nan]] 
Find the missing data of the said array: 
 [[False False  True False]
 [False False False False]
 [False  True False  True]]


##### 2. Write a NumPy program to check whether two arrays are equal (element wise) or not.

In [3]:
### code here
def isequal(x,y):
    equal = True
    for i,j in zip(x,y):
        for a,b in zip(i,j):
            if a==b:
                equal = True
            else:
                equal = False
    return equal



print(isequal(np.arange(1,10).reshape(3,3),(np.arange(1,10).reshape(3,3))))
print(isequal(np.random.randint(1,10,(3,3)),np.random.randint(1,10,(3,3))))

True
False


In [4]:
# method 2
def isequal(x,y):
    return np.array_equal(x,y)
print(isequal(np.arange(1,10).reshape(3,3),(np.arange(1,10).reshape(3,3))))
print(isequal(np.random.randint(1,10,(3,3)),np.random.randint(1,10,(3,3))))

True
False


###### 3. Write a NumPy program to create a 4x4 array with random values, now create a new array from the said array swapping first and last rows.

In [5]:
## code here
Original_array = np.arange(16).reshape(4,4)
print(f'Original_array:\n{Original_array}')
Original_array[[0,-1]] = Original_array[[-1,0]]
print(f'New array after swapping first and last rows of the said array:\n {Original_array}')


Original_array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
New array after swapping first and last rows of the said array:
 [[12 13 14 15]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]]


###### 4. Write a NumPy program to convert a list and tuple into arrays.

In [7]:
#### code here
print(f'Array using tuple :\n{np.array((1,2,3,4,5,6,7,8,9)).reshape(3,3)}')
print(f'Array using list :\n{np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)}')

Array using tuple :
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Array using list :
[[1 2 3]
 [4 5 6]
 [7 8 9]]


###### 5. Write a NumPy program to find common values between two arrays.

In [8]:
### code here
arr = np.random.randint(1,10,(3,3))
arr1 = np.random.randint(1,10,(3,3))
np.intersect1d(arr,arr1)

array([1, 2, 4, 5, 6])

###### 6. Write a NumPy program to create a new shape to an array without changing its data.

In [9]:
### code here

print(f'Array with shape (1,9):\n{np.arange(1,10).reshape(1,9)}\n')
print(f'Array with shape (9,1):\n{np.arange(1,10).reshape(9,1)}\n')
print(f'Array with shape (3,3):\n{np.arange(1,10).reshape(3,3)}\n')

Array with shape (1,9):
[[1 2 3 4 5 6 7 8 9]]

Array with shape (9,1):
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]

Array with shape (3,3):
[[1 2 3]
 [4 5 6]
 [7 8 9]]



###### 7. Write a NumPy program to count the frequency of unique values in numpy array.

In [11]:
### code here
arr = np.array([10,10,20,10,20,20,20,30,30,50,40,40])
print(f'Original array: \n{arr}')
freq,count = np.unique(arr, return_counts=True)
print(f'Frequency of unique values of the said array:\n{freq} \n{count}')


Original array: 
[10 10 20 10 20 20 20 30 30 50 40 40]
Frequency of unique values of the said array:
[10 20 30 40 50] 
[3 4 2 2 1]


###### 8. Write a NumPy program to broadcast on different shapes of arrays where p(3,3) + q(3).

In [13]:
### code here
arr1 = np.array([0,0,0,1,2,3,4,5,6]).reshape(3,3)
arr2 = np.array([10,11,12])
print(f'Original Arrays:\nArray_1\n{arr1}\nArray_2\n{arr2}')
print()
print(f'New Array: \n{arr1+arr2}')

Original Arrays:
Array_1
[[0 0 0]
 [1 2 3]
 [4 5 6]]
Array_2
[10 11 12]

New Array: 
[[10 11 12]
 [11 13 15]
 [14 16 18]]


###### 9. Write a NumPy program to extract all the elements of the second row from a given (4x4) array.

In [15]:
### code here
arra_data = np.arange(0,16).reshape((4, 4))
print("Original array:")
print(arra_data)
print("\nExtracted data: Second row")
print(arra_data[1,:])

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Second row
[4 5 6 7]


###### 10. Write a NumPy program to extract third and fourth elements of the first and second rows from a given (4x4) array.

In [17]:
## code here
arr = np.arange(16).reshape(4,4)
print(f'Original array:\n{arr}')
print(f'Extracted data: Third and fourth elements of the first and second rows:\n{arr[:2,2:4]}')


Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Extracted data: Third and fourth elements of the first and second rows:
[[2 3]
 [6 7]]


###### 11. Write a NumPy program to get the dates of yesterday, today and tomorrow.

In [19]:
today = np.datetime64('today', 'D')
yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')
print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)

Yesterday: 2025-02-14
Today: 2025-02-15
Tomorrow: 2025-02-16


###### 12. Write a NumPy program to find the first Monday in May 2017.

In [20]:
## code here
date = np.busday_offset('2017-05',0,weekmask='Mon')
print(f'First Monday in may 2017:\n{date}')

First Monday in may 2017:
2017-05-01
