<a href="https://colab.research.google.com/github/Jayakrishna143/numpy/blob/main/P_Jayakrishnareddy355_numpy3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

- Rule 1: If the two arrays different in their number of dims, the shape of the
one with fewer dimensions is added with ones on its left side.
- Rule 2: If the shape of the two arrays does not match in any dimension, the array
with shape equal to 1 in that dimension is stretched to match the other shape.
- Rule 3: If in any dimension the sizes disagree and neither is equal to 1, an error is
raised.


In [8]:
array1 = np.random.randint(1,10,(3,4)) # array with size (3,4)
array2 = np.random.randint(1,10,(4,)) # array wiht size (4,)
sum_array = array1 + array2
mul_array = array1 * array2
print(f'Element-wise addition = \n{sum_array}')
print(f'Element-wise multiplication:\n{mul_array}')
# rule 1 the array with less dim is added with 1 on its left side
# rule 2 The array with shape 1 is streched to match size of other array

element-wise addition = 
[[17 11  8  5]
 [17 12 10  2]
 [16  8 13  7]]
element-wise multiplication:
[[72 28  7  4]
 [72 35 21  1]
 [64  7 42  6]]


In [10]:
array1 = np.random.randint(20,30,(3,4)) # array with size (3,4)
array2 = np.random.randint(1,10,(3,5)) # array with size (3,5)
sum_array = array1 + array2
mul_array = array1 * array2
print(f'Element-wise addition = \n{sum_array}')
print(f'Element-wise multiplication:\n{mul_array}')
# here the addition and multiplication doesnt happen bcos
#rule 1: The dimensions of both the array are same ie both are 2D arrays and no 1s are added
#rule 2: Because both are of same dims and no 1 are added there is no way to increase the size to match both array
# as both sizes are not matched multiplication or additon are not performed and outputs error

ValueError: operands could not be broadcast together with shapes (3,4) (3,5) 

####`rand : `
- This is a method to give random numbers,but the range of values given are between 0 and 1 only
- Gives float values
- only takes size or array as argument
####` randn : `
- This is method to give random float values.
- the default mean is 0 and diviation is 1 so may get negative float values
- It only takes size as input
####`rnadint : `
- This method as name specifies give interger values
- it takes the range of numbers between which the random values are needed and also size as tuple
####`uniform : `
- this method generates random float values
- this is similar to rand but can take range of values needed and also size of array needed

In [11]:
array1 = np.random.rand(3,5)
array2 = np.random.randn(3,5)
array3 = np.random.randint(1,10,(3,5))
array4 = np.random.uniform(1,10,(3,5))
array1,array2,array3,array4

(array([[0.81224203, 0.71740186, 0.29131805, 0.4441746 , 0.59992102],
        [0.72162688, 0.51435931, 0.21346875, 0.60395696, 0.42396414],
        [0.26527536, 0.1171481 , 0.6005027 , 0.45466397, 0.75658562]]),
 array([[ 1.7558015 ,  0.1152907 ,  0.70331146,  0.75014245,  0.38663677],
        [-0.56480118,  0.88976254,  1.24525701,  0.90367587,  1.28603696],
        [-0.31338713,  0.94606897, -0.67282966,  0.78757625,  1.26846089]]),
 array([[1, 3, 7, 9, 4],
        [2, 8, 6, 3, 6],
        [1, 5, 7, 1, 8]]),
 array([[7.83408265, 7.82107431, 7.28121069, 1.61698719, 6.5992167 ],
        [3.82532358, 2.93394965, 3.57322541, 2.67150791, 7.03732066],
        [5.39890205, 7.30672039, 4.31175517, 6.3457723 , 2.55505322]]))