<a href="https://colab.research.google.com/github/Jayakrishna143/numpy/blob/main/P_Jayakrishnareddy355_numpy5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a,b = np.array([1,2,3]),np.array([4,5,6])
print(f'Method 1 of vertical stacking two arrays: \n{np.stack([a,b])} -> created an array of shape,{np.stack([a,b]).shape}')
print(f'\nMethod 2 of vertical stacking two arrays: \n{np.vstack([a,b])} -> created an array of shape,{np.vstack([a,b]).shape}\n')

'''The result of stacking two 1D arrays vertically created a 2D array of shape (2,3)'''

Method 1 of vertical stacking two arrays: 
[[1 2 3]
 [4 5 6]] -> created an array of shape,(2, 3)

Method 2 of vertical stacking two arrays: 
[[1 2 3]
 [4 5 6]] -> created an array of shape,(2, 3)



'The result of stacking two 1D arrays vertically created a 2D array of shape (2,3)'

In [3]:
# There are two ways of stacking a 2d Array one using
a,b = np.random.randint(1,10,(2,3)),np.random.randint(1,10,(2,3))
print(f'Method 1 of vertical stacking two 2d arrays: \n{np.stack([a,b])} -> created an array of shape,{np.stack([a,b]).shape}')
print(f'\nMethod 2 of vertical stacking two 2d arrays: \n{np.vstack([a,b])} -> created an array of shape,{np.vstack([a,b]).shape}\n')
'''While using a simple stack method resulted in a 3d array of size(2,2,3) where as vstack resulted in a 2d array of shape(4,3)'''

Method 1 of vertical stacking two 2d arrays: 
[[[7 7 3]
  [3 8 4]]

 [[2 8 3]
  [5 3 1]]] -> created an array of shape,(2, 2, 3)

Method 2 of vertical stacking two 2d arrays: 
[[7 7 3]
 [3 8 4]
 [2 8 3]
 [5 3 1]] -> created an array of shape,(4, 3)



'While using a simple stack method resulted in a 3d array of size(2,2,3) where as vstack resulted in a 2d array of shape(4,3)'

In [4]:
x,y = np.array([1,2,3]),np.array([4,5,6])
print(f'Method 1 of Horizontal stacking two 1D arrays: \n{np.stack([x,y],axis=1)} -> created an array of shape,{np.stack([x,y],axis = 1).shape}')
print(f'\nMethod 2 of Horizontal stacking two 1D arrays: \n{np.hstack([x,y])} -> created an array of shape,{np.hstack([x,y]).shape}\n')

'''While using a simple stack method with axis =1 resulted in a 2d array of size(3,2) where as hstack resulted in a 2d array of shape(6,)'''

Method 1 of Horizontal stacking two 1D arrays: 
[[1 4]
 [2 5]
 [3 6]] -> created an array of shape,(3, 2)

Method 2 of Horizontal stacking two 1D arrays: 
[1 2 3 4 5 6] -> created an array of shape,(6,)



'While using a simple stack method with axis =1 resulted in a 2d array of size(3,2) where as hstack resulted in a 2d array of shape(6,)'

In [5]:
A,B = np.random.randint(1,10,(3,2)),np.random.randint(1,10,(3,2))
print(f'Method 1 of vertical stacking two 2d arrays: \n{np.stack([A,B],axis =1)} -> created an array of shape,{np.stack([A,B],axis =1).shape}')
print(f'\nMethod 2 of vertical stacking two 2d arrays: \n{np.hstack([A,B])} -> created an array of shape,{np.hstack([A,B]).shape}\n')

'''While using a simple stack method with axis= 1 resulted in a 3d array of size(3,2,2) where as hstack resulted in a 2d array of shape(3,4)'''

Method 1 of vertical stacking two 2d arrays: 
[[[3 7]
  [1 6]]

 [[9 8]
  [9 4]]

 [[9 4]
  [3 5]]] -> created an array of shape,(3, 2, 2)

Method 2 of vertical stacking two 2d arrays: 
[[3 7 1 6]
 [9 8 9 4]
 [9 4 3 5]] -> created an array of shape,(3, 4)



'While using a simple stack method with axis= 1 resulted in a 3d array of size(3,2,2) where as hstack resulted in a 2d array of shape(3,4)'

In [6]:
np.split(np.array([10,20,30,40,50,60]),3)

[array([10, 20]), array([30, 40]), array([50, 60])]

In [7]:
np.split(np.array([i for i in range(10,101) if i%10 ==0]),[3,5,9])

[array([10, 20, 30]), array([40, 50]), array([60, 70, 80, 90]), array([100])]