<a href="https://colab.research.google.com/github/Jayakrishna143/numpy/blob/main/P_Jayakrishna_Redy_Numpy_assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### NumPy Exercises
##### Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.
##### IMPORTANT NOTE! Make sure you don't run the cells directly above the example output shown, otherwise you will end up writing over the example output!

In [ ]:
import numpy as np

#####1.  Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

In [ ]:
### code here
print(f'An array of 10 Zeros: \n {np.zeros(10)}')
print(f'An array of 10 Ones: \n {np.ones(10)}',)
print(f'An array of 10 fives: \n {np.full((1,10),5)}',)

An array of 10 Zeros: 
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 Ones: 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives: 
 [[5 5 5 5 5 5 5 5 5 5]]


In [ ]:
## sample output


An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


#####2.  Write a NumPy program to create an array of the integers from 30 to 70.

In [ ]:
print(f'Array of the integers from 30 to 70:\n {np.arange(30,71)}')


Array of the integers from 30 to 70:
 [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [ ]:
### sample output

Array of the integers from 30 to70
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


######3. Write a NumPy program to create an array of all the even integers from 10 to 50.

In [ ]:
### code here
x = np.arange(10,50)
print('Array of all the even integers from 10 to 50:')
print(x[::2])

Array of all the even integers from 10 to 50:
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [ ]:
## sample output


Array of all the even integers from 10 to 50
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


######4. Write a NumPy program to create a 3x3 identity matrix.

In [ ]:
### code here
print(f'3x3 matrix:\n { np.eye(3)}')

3x3 matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
## sample output

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


##### 5. Write a NumPy program to generate a random number between 0 and 1

In [ ]:
### code here
print(f'Random number between 0 and 1: \n {[np.random.rand()]}')

Random number between 0 and 1: 
 [0.4955534229806342]


In [ ]:
## sample output

Random number between 0 and 1:
[0.40400053]


###### 6. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

In [ ]:
## code here
print(f'15 random numbers from a standard normal distribution:\n {np.random.normal(0,1,(15))}')

15 random numbers from a standard normal distribution:
 [-0.22615159  0.24738867 -1.00351734 -0.3162913  -0.2511493  -0.64372917
 -0.09068351  1.01831606  1.19501358 -0.25520297  0.26455049  2.32034906
  0.55605684  0.74149799  0.35132343]


In [ ]:
## sample output

15 random numbers from a standard normal distribution:
[ 0.68439314  1.50916987 -0.75364839  0.1038106   0.07789927 -0.15349755
  1.78151615  0.49989426  0.18791322 -1.51931266 -0.55512066  2.02808972
  0.37648568  0.57999878 -0.31095957]


###### 7. Write a NumPy program to create a 3X4 array using and iterate over it.

In [ ]:
## code here
x=np.random.randint(10,22,(3,4))
print(f'Original Array: \n {x}\n Each element of the array is:')
for i in x:
    for j in i:
        print(j, end=" " )

Original Array: 
 [[17 21 15 19]
 [21 20 14 10]
 [17 16 18 13]]
 Each element of the array is:
17 21 15 19 21 20 14 10 17 16 18 13 

In [ ]:
## sample output

Original array:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Each element of the array is:
10 11 12 13 14 15 16 17 18 19 20 21 

###### 8. Write a NumPy program to multiply the values ​​of two given vectors.

In [ ]:
## code here
print(f'Vector-1 \n{np.array([1,8,3,5])}\nVector-2 \n{np.array([10,1,4,10])} \nMultiply the values of two vectors \n{np.multiply(np.array([1,8,3,5]),np.array([10,1,4,10]))}')

Vector-1 
[1 8 3 5]
Vector-2 
[10  1  4 10] 
Multiply the values of two vectors 
[10  8 12 50]


In [ ]:
## sample output

Vector-1
[1 8 3 5]
Vector-2
[10  1  4 10]
Multiply the values of two said vectors:
[10  8 12 50]


###### 9. Write a NumPy program to reverse an array (first element becomes last).

In [ ]:
### code here
x = np.array([12,13,14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,32,33, 34, 35, 36, 37])
print(f'Original array: \n{x} \n Revese array: \n{x[::-1]}')

Original array: 
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37] 
 Revese array: 
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [ ]:
## sample output

Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


##### 10. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [ ]:
## code here
x= np.zeros((5,5),dtype='int8')
np.fill_diagonal(x,[1,2,3,4,5])
print(x)


[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [ ]:
## sample output

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


###### 11. Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array.

In [ ]:
## code here
x= np.arange(4).reshape(2,2)
print(f'Original array:\n{x} \n Sum of all elements:\n{np.sum(x)}\n sum of each column: \n{np.sum(x,axis = 0)}\n sum of each row: \n{np.sum(x,axis = 1)}')

Original array:
[[0 1]
 [2 3]] 
 Sum of all elements:
6
 sum of each column: 
[2 4]
 sum of each row: 
[1 5]


In [ ]:
## sample output

Original array:
[[0 1]
 [2 3]]
Sum of all elements:
6
Sum of each column:
[2 4]
Sum of each row:
[1 5]


###### 12. Write a NumPy program to compute the inner product of two given vectors.

In [ ]:
## code here
x = np.array([4,5])
y = np.array([7,10])
print(f'Original vectors:\n{x}\n{y}\nInner product of said vectors:\n{np.dot(x,y)}')

Original vectors:
[4 5]
[ 7 10]
Inner product of said vectors:
78


In [ ]:
## sample output

Original vectors:
[4 5]
[ 7 10]
Inner product of said vectors:
78
