<a href="https://colab.research.google.com/github/Jayakrishna143/numpy/blob/main/Pjayakrishnareddy_355_numpy_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np
print(f'Array filled with ones: \n{np.ones((3,3))}\n')
print(f'Array with ones on the diagonal: \n{np.diag(np.array([1,1,1]))}\n')
print(f'Array filled with zeros: \n{np.zeros((3,3))}')

Array filled with ones: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Array with ones on the diagonal: 
[[1 0 0]
 [0 1 0]
 [0 0 1]]

Array filled with zeros: 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
arr=np.random.randint(1,10,(3,3))
print(f'mean of the array is: \n{np.mean(arr)}\n')
print(f'median of the array is: \n{np.median(arr)}\n')
print(f'standard deviation of the array is: \n{np.std(arr)}\n')

mean of the array is: 
5.444444444444445

median of the array is: 
5.0

standard deviation of the array is: 
2.753224820747526



In [14]:
arr = np.empty((3, 4))
arr.shape
'''Empty array is not truely empty it has a shape of (3,4)'''

(3, 4)