<a href="https://colab.research.google.com/github/Jayakrishna143/numpy/blob/main/policepatelJayakrishna355_numpy3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

###Q1
####A.Generata a numpy array with arange() function.
- access element at ehe second index of the NumPy array
- slice the first three elements

In [2]:
arr = np.arange(10)
print("Original Array:", arr)

#elements at the second index
print("Element at index 2:", arr[2])

# first three elements
print("First three elements:", arr[:3])


Original Array: [0 1 2 3 4 5 6 7 8 9]
Element at index 2: 2
First three elements: [0 1 2]


#### Create a 2d array.
- Acess the element in the second row and third column of the 2d array.
- Slice the first two rows and columns of the 2D array

In [10]:
# 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr_2d)

# element in second row, third column
print("Element at (2,3):", arr_2d[1, 2])

# first two row and first two columns
print("First teo rows, first two columns:\n", arr_2d[:2, :2])

2D Array:
 [[1 2 3]
 [4 5 6]]
Element at (2,3): 6
First teo rows, first two columns:
 [[1 2]
 [4 5]]


###Q2
#### A. Create an array that includes values from 1 to 10 wiht a step of 2.
#### B, create a 2x3 array using reshape() from 1D array with values 1 to 6

In [7]:
# array from 1 to 10 with step 2
arr_step = np.arange(1, 11, 2)
print("Array with step 2:", arr_step)

# 2x3 array using reshape
arr_reshaped = np.arange(1, 7).reshape(2, 3)
print("Reshaped 2x3 Array:\n", arr_reshaped)

Array with step 2: [1 3 5 7 9]

Reshaped 2x3 Array:
 [[1 2 3]
 [4 5 6]]


###Q3
#### Create a 3D array print its shape and then use squeeze() to remove the singleton dimension. Display both the input and output arrays along with their shapes.


In [12]:
# 3d array
arr_3d = np.array([[[1, 2, 3]]])
print("\nOriginal 3D Array:", arr_3d)
print("Original Shape:", arr_3d.shape)
# 3d_array squeezed
arr_squeeze = np.squeeze(arr_3d)
print("\nSqueezed Array:", arr_squeeze)
print("Squeezed Shape:", arr_squeeze.shape)


Original 3D Array: [[[1 2 3]]]
Original Shape: (1, 1, 3)

Squeezed Array: [1 2 3]
Squeezed Shape: (3,)


###Q4
#### Create a  2D NumPy array and use np.expand_dims() to add singleton dimensions. Show the array and its shape before and after each operation.

In [15]:
#2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\nOriginal 2D Array:\n", arr_2d)
print("Original Shape:", arr_2d.shape)

# Expand dimensions along axis 0
arr_exp1 = np.expand_dims(arr_2d, axis=0)
print("Expanded along axis 0:\n", arr_exp1)
print("New Shape:", arr_exp1.shape)

# Expand dimensions along axis 2
arr_exp2 = np.expand_dims(arr_2d, axis=2)
print("Expanded along axis 2:\n", arr_exp2)
print("New Shape:", arr_exp2.shape)


Original 2D Array:
 [[1 2 3]
 [4 5 6]]
Original Shape: (2, 3)
Expanded along axis 0:
 [[[1 2 3]
  [4 5 6]]]
New Shape: (1, 2, 3)
Expanded along axis 2:
 [[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
New Shape: (2, 3, 1)
